[project]
name = "weatherapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fmiopendata>=0.5.0",
    "nicegui>=3.2.0",
]
